name: Update Repository Stats

on:
  push:
    branches:
      - test-workflow
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Update Repository Stats
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_README }}
        run: |
          python scripts/update_stats.py "${{ secrets.UPDATE_README }}"

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update repository stats'
          git push origin test-workflow
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}